# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: west

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: pubsub-lib
      url-base: https://github.com/dbortoluzzi
    - name: cJSON-lib
      url-base: https://github.com/DaveGamble
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v2.7.1
      import: true
      path: wzephyr
    - name: pubsub
      remote: pubsub-lib
      revision: master
      path: lib/pubsub
    - name: cJSON
      remote: cJSON-lib
      revision: master
      path: lib/cJSON
      
